spring:
  application:
    name: elias.camacho
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ECR23
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update